name: cliff_pickleball
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  animated_splash_screen: ^1.3.0
  basic_utils: ^5.7.0
  connectivity_plus: ^6.0.5
  currency_text_input_formatter: ^2.2.5
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.4
  go_router: ^14.2.8
  google_fonts: ^6.2.1
  http_interceptor: ^2.0.0
  injectable: ^2.4.4
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.2
  optional: ^6.1.0+1
  page_transition: ^2.1.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
