name: cliff_pickleball
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  animated_splash_screen: ^1.3.0
  any_link_preview: ^3.0.2
  awesome_dialog: ^3.2.1
  basic_utils: ^5.7.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.4
  connectivity_plus: ^6.0.5
  contacts_service:
    git:
      url: https://github.com/ArturoSojo/flutter_contacts.git
  currency_text_input_formatter: ^2.2.5
  device_info_plus: ^11.1.1
  dio: ^5.7.0
  dotted_border: ^2.1.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  file_picker: ^8.1.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.4
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_font_icons: ^2.2.7
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.8.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  go_router: ^14.2.8
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  google_sign_in: ^6.2.1
  http_interceptor: ^2.0.0
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  injectable: ^2.4.4
  intl: ^0.19.0
  ionicons: ^0.2.2
  just_audio: ^0.9.42
  like_button: ^2.0.5
  loading_overlay: ^0.4.2
  location: ^7.0.1
  logger: ^2.4.0
  lottie: ^3.1.2
  new_version_plus: ^0.0.12
  optional: ^6.1.0+1
  page_transition: ^2.1.0
  animations: ^2.0.11
  path_provider: ^2.1.5
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pull_to_refresh: ^2.0.0
  record: ^5.2.0
  routemaster: ^1.0.1
  share_plus: ^10.1.2
  shared_preferences: ^2.3.2
  sizer: ^3.0.4
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.4.1
  story: ^1.1.0
  swipe_to: ^1.0.6
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  velocity_x: ^4.2.1
  video_player: ^2.9.2
  workmanager: ^0.5.2
  chat_bubbles: ^1.6.0
  flutter_chat_bubble: ^2.0.2
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  baseflow_plugin_template: ^2.2.0
  firebase_app_check: ^0.3.1+7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf