// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWjaHOGmisWv8Sew0t7yc1DfSzf7j5Sv0',
    appId: '1:1038856538748:web:d7856c208cd11de40397f9',
    messagingSenderId: '1038856538748',
    projectId: 'cliff-pickleball',
    authDomain: 'cliff-pickleball.firebaseapp.com',
    storageBucket: 'cliff-pickleball.firebasestorage.app',
    measurementId: 'G-N3E5GP6ZGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBugoHc4FG_gqDdbK9Ur9CszAmYk7pIpqM',
    appId: '1:1038856538748:android:4f70904fa70dcb710397f9',
    messagingSenderId: '1038856538748',
    projectId: 'cliff-pickleball',
    storageBucket: 'cliff-pickleball.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMuALKddxc2c9EU5WxSwL1IgeEHva10RU',
    appId: '1:1038856538748:ios:ea8f77eed5af55140397f9',
    messagingSenderId: '1038856538748',
    projectId: 'cliff-pickleball',
    storageBucket: 'cliff-pickleball.firebasestorage.app',
    iosBundleId: 'com.example.cliffPickleball',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMuALKddxc2c9EU5WxSwL1IgeEHva10RU',
    appId: '1:1038856538748:ios:ea8f77eed5af55140397f9',
    messagingSenderId: '1038856538748',
    projectId: 'cliff-pickleball',
    storageBucket: 'cliff-pickleball.firebasestorage.app',
    iosBundleId: 'com.example.cliffPickleball',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWjaHOGmisWv8Sew0t7yc1DfSzf7j5Sv0',
    appId: '1:1038856538748:web:57ab7a6f7c84ed6d0397f9',
    messagingSenderId: '1038856538748',
    projectId: 'cliff-pickleball',
    authDomain: 'cliff-pickleball.firebaseapp.com',
    storageBucket: 'cliff-pickleball.firebasestorage.app',
    measurementId: 'G-ST0B8F8X8G',
  );
}
