String translate(String message) {
  switch (message.toUpperCase()) {
    case "AUTH_DEVICE_LOCKED":
      return "DISPOSITIVO BLOQUEADO";
    case "DEVICE_IS_LOCKED":
      return "DISPOSITIVO BLOQUEADO";
    case "INVALID_TOKEN":
      return "TOKEN INVÁLIDO";
    case "ISO_SERVER_NOT_AVAILABLE":
      return "ISO SERVER NO DISPONIBLE";
    case "SOFTWARE CAUSED CONNECTION ABORT":
      return "CONEXIÓN DE INTERNET INTERRUMPIDA, POR FAVOR CONSULTE LA ÚLTIMA TRANSACCIÓN";
    case "WALLET_DEVICE_IS_NOT_ASSIGNED_TO_A_WALLET_STORE":
      return "EL DISPOSITIVO NO SE ENCUENTRA ASIGNADO A NINGUNA TIENDA. POR FAVOR INGRESE AL PORTAL DE CREDICARDPAGOS A LA SECCIÓN DE PINPAD-ADMIN Y ASIGNELO, O COMUNIQUESE CON SU EJECUTIVO DE VENTAS PARA TERMINAR LA CONFIGURACIÓN DEL DISPOSITIVO";
    case "TDC":
      return "CREDITO";
    case "TDD":
      return "DEBITO";
    case "TRANSACTION_TERMINATED":
      return "TRANSACCIÓN ANULADA";
    case "YOU'RE NOT ALLOWED TO ACCESS THIS RESOURCE":
      return "NO TIENES PERMISO PARA ACCEDER A ESTE RECURSO";
    case "DEVICE_INVALID":
      return "DISPOSITIVO INVÁLIDO";
    case "WALLET_DEVICE_IS_INACTIVE":
      return "DISPOSITIVO INACTIVO";
    case "WALLET_DEVICE_NOT_FOUND":
      return "DISPOSITIVO NO ENCONTRADO";
    case "STATE ANULATED":
      return "ESTADO ANULADO";
    case "CANCEL":
      return "TRANSACCIÓN CANCELADA";
    case "INPUT_PIN_ING":
      return "COLOQUE EL PIN DE LA TARJETA";
    case "PROCESSING":
      return "PROCESANDO";
    case "ACCESS_DENIED":
      return "ACCESO DENEGADO";
    case "504_GATEWAY_TIMEOUT":
      return "ERROR EN CONEXION CON EL SERVIDOR";
    case "THIS_ROUTE_DOES_NOT_EXIST":
      return "NO EXISTE ESTA RUTA";
    case "USER_NOT_FOUND":
      return "USUARIO NO EXISTE";
    case "UNAUTHORIZED":
      return "INAUTORIZADO";
    case "USER_CREDENTIALS_NOT_FOUND":
      return "ESTE USUARIO NO POSEE CREDENCIALES";
    case "PLEASE_WAIT":
      return "ESPERE UN MOMENTO, NO RETIRE LA TARJETA";
    case "REMOVE_CARD":
      return "POR FAVOR REMUEVE LA TARJETA";
    case "DEVICE_RESET":
      return "ERROR DISPOSITIVO OCUPADO EN OTRA TRANSACCIÓN";
    case "CREDICARD_RESPONSE_UNSUCCESSFUL":
      return "RESPUESTA FALLIDA";
    case "FAILED_REQUEST":
      return "SOLICITUD FALLIDA";
    case "ERROR_TIMEOUT":
      return "ERROR TIEMPO DE RESPUESTA";
    case "APPROVED":
      return "APROBADO";
    case "FAILED":
      return "FALLIDA";
    case "PAY":
      return "COMPRA";
    case "REJECTED":
      return "RECHAZADA";
    case "ANULATED":
      return "ANULADO";
    case "ANULATED_REJECTED":
      return "ANULACIÓN RECHAZADA";
    case "ANULATE":
      return "ANULACIÓN";
    case "NO_CYCLES_FOUND_FOR_QUERY":
      return "NO HAY LOTES ABIERTOS";
    case "OPERATION_REQUEST_NOT_FOUND":
      return "SOLICITUD DE OPERACIÓN NO ENCONTRADA";
    case "OPERATION_REQUEST_CAN_NOT_BE_ANULATED":
      return "SOLICITUD DE OPERACIÓN NO SE PUEDE ANULAR";
    case "INVALID_USER_OR_PASSWORD":
      return "USUARIO O CONTRASEÑA INVÁLIDA";
    case "THERE_IS_NO_TRANSACIONS_FOR_DEVICE":
      return "NO HAY TRANSACIONES PARA EL DISPOSITIVO";
    case "BAD_REQUEST":
      return "SOLICITUD FALLIDA";
    case "ROLE_NOT_FOUND":
      return "ROL NO ENCONTRADO";
    case "CLIENT_NOT_FOUND":
      return "CLIENTE NO ENCONTRADO";
    case "PASSWORD_EXPIRED":
      return "CONTRASEÑA EXPIRADA";
      case "MOVISTAR_POSTPAID_DEBT_IS_NOT_POSITIVE":
      return "NO CUENTA CON UNA DEUDA MOVISTAR POSPAGO";
    case "SERVICE_IS_NOT_REGISTERED_IN_INVENTORY_PRODUCTS_":
      return "EL SERVICIO NO ESTÁ REGISTRADO EN EL INVENTARIO DE PRODUCTOS";
    case "COLLECT_CHANNEL_NOT_FOUND":
      return "CANAL NO ENCONTRADO";
    case "SERVICE_PAY_INVENTORY_CANNOT_GO_BELOW_":
      return "EL INVENTARIO NO PUEDE ESTAR POR DEBAJO DE";
    case "SERVICE_PAY_ALLY_IS_INACTIVE":
      return "ALIADO SUSPENDIDO";
    case "ACCOUNT_HAS_NO_DEBT_TO_PAY":
      return "LA CUENTA NO POSEE DEUDAS";
    case "SERVICE_PAY_BUYER_INVENTORY_NOT_FOUND":
      return "INVENTARIO NO ENCONTRADO";
    case "DUPLICATED_PAY":
      return "PAGO DUPLICADO";
    case "SERVICE_PAY_INVENTORY_NOT_FOUND":
      return "INVENTARIO NO ENCONTRADO";
    case "SALE_ORDER_BALANCE_PAYMENT":
      return "ORDEN DE VENTA AUTORIZADO";
    case "PREPAY":
      return "PREPAGO";
    case "POSTPAID":
      return "POSPAGO";
    case "SERVICE_IS_NOT_ABLE_TO_CONNECT_":
      return "EL SERVICIO NO PUEDE CONECTARSE";
    case "IN":
      return "ENTRADA";
    case "OUT":
      return "SALIDA";
    case "PAYMENT":
      return "PAGO";
    case "COMMISSION":
      return "COMISIÓN";
    case "LENGTH":
      return "ERROR EN LA LONGITUD DE LA CUENTA";
    case "DEEGLE_API_PAYMENTS_INTEGRATION_ERROR":
      return "ERROR DE INTEGRACIÓN DE PAGOS API DEEGLE";
    case "BANCARIBE_MOBILE_PAYMENT_SEARCH":
      return "BÚSQUEDA DE PAGO MÓVIL BANCARIBE";
    case "API_FAILURE":
      return "FALLA DE API";
    case "COLLECT_METHOD_NOT_FOUND":
      return "MÉTODO DE COLECCIÓN NO ENCONTRADO";
    case "AMOUNT_TO_PAY_CANNOT_BE_OVER_MOVISTAR_POSTPAID_DEBT":
      return "LA CANTIDAD A PAGAR NO PUEDE SER SUPERIOR A LA DEUDA POSPAGO DE MOVISTAR";
    case "FAILED_TO_GET_TOKEN_FROM_BANCARIBE_PAYMENT_API":
      return "NO SE PUEDE OBTENER EL TOKEN DE LA API DE PAGO DE BANCARIBE";
    case "SERVICE_PAY_AMOUNT_MUST_BE_LOWER_THAN_":
      return "EL MONTO DEL PAGO DEL SERVICIO DEBE SER INFERIOR A";
    case "MOVISTAR_POSTPAID_IS_DISABLED_BY_SCHEDULE":
      return "MOVISTAR POSPAGO SE DESHABILITA POR HORARIO";
    case "SERVICE_PAY_INVALID_ACCOUNT_NUMBER":
      return "NÚMERO DE CUENTA INVÁLIDO";
    case "MOVISTAR_POSTPAID_ERROR":
      return "ERROR MOVISTAR POSTPAGO";
    case "SERVICE_PAY_AMOUNT_MUST_BE_MULTIPLE_OF_":
      return "EL MONTO NO ES MULTIPLO DE ";
    case "SERVICE_PAY_AMOUNT_MUST_BE_HIGHER_THAN_":
      return "EL MONTO DEL PAGO DEL SERVICIO DEBE SER SUPERIOR A ";
    case "CANTV_INTERNET":
      return "CANTV CTA. CONTRATO";
    case "MOVISTAR_POSTPAID":
      return "MOVISTAR POSPAGO";
    case "MOVILNET_POSTPAID":
      return "MOVILNET POSPAGO";
    case "ARIESCO_SIMPLE_TV_POSTPAID":
      return "SIMPLETV POSPAGO";
    case "ARIESCO_DIGITEL_PREPAID":
      return "DIGITEL RECARGA";
    case "ARIESCO_MOVISTAR_PREPAID":
      return "MOVISTAR RECARGA";
    case "ARIESCO_INTER_PREPAID":
      return "INTER RECARGA";
    case "ARIESCO_MOVILNET_PREPAID":
      return "MOVILNET RECARGA";
    case "TOKEN_EXPIRED":
      return "TOKEN EXPIRADO";
    case "NEW-SALES":
      return "NUEVA VENTA";
    case "LAST-TRANSACTION":
      return "ULTIMA";
    case "TRANSACTIONS":
      return "TRANSACCIONES";
    case "SIMPLE-REPORT":
      return "REPORTE";
    case "TOTAL-REPORT":
      return "REPORTE";
    case "DETAILED-REPORT":
      return "REPORTE";
    case "CLOSE-POS":
      return "CIERRE";
    case "TECHNICAL-MANAGEMENT":
      return "ECHO TEST";
    case "EXTERNAL_SERVICE_PAY_SERVICE_IS_NOT_AVAILABLE":
      return "SERVICIO EXTERNO DE RECARGO NO ESTÁ DISPONIBLE";
    case "EXTERNAL_SERVICE_PAY_SERVICE_MSG_ERROR":
      return "ERROR DE SERVICIO DE RECARGA";
    case "SERVICE_PAY_PAYMENT_ERROR":
      return "ERROR DE PAGO";
    default:
      return message;
  }
}
